class Contributers {
  List<String> contributers = [
    'Nirbhay-nrb',
    'Shreyasrana18',
    'Manv3ndra',
    'Palash2003',
    'PARAVPREET17',
    'thetarandhiman',
    'alishaac',
    'aryan-401',
    'DevanshUpadhyay26',
    'simranbhalla3',
    'krohitk17',
    '2002-ishaan',
    'manveersingh29',
    'Pranvee_Vashisht',
    'SukritSethi',
    'Red-0111',
    'nirad17',
    'deepankarvarma',
    'adityasrathore',
    'DvnOshin',
    'yuktagopalani',
    'SayanKabir',
    'Digisata',
    'CodeOnnnn',
    'rudratejC',
    'Aman-Ladla',
    'Palak-Yadav',
    'PRAJJWALmehta',
    'Alfaridzi',
    'pavankalyan0424',
    'EbhomenyeEmmanuel',
    'namanbohra',
    'Anuragvij55',
    'aman1210',
    'arjun-710',
    'sanxy',
    'Hritik Baliyan',
    'Ntare Guy',
    'ayushmanbedi',
    'javeriatabassum145',
    'Rohan Doshi',
    'Ansh Rathod',
    'itsmurphy',
    'NuCLeUs2',
    'Gulshan Jakhon',
    'akashlilhare',
    'Suyog Kokaje',
    // Add your GitHub Username here (please add "," also)
  ];

  List<String> getList() {
    return contributers;
  }
}
